In [1]:
import numpy as np

# transpuesta de una matriz

El atributo .T es equivalente al método .transpose()

In [2]:
m1 = np.arange(10).reshape(2, 5)
print(m1)
print('\n')
print(m1.T)

[[0 1 2 3 4]
 [5 6 7 8 9]]


[[0 5]
 [1 6]
 [2 7]
 [3 8]
 [4 9]]


In [3]:
print(m1.transpose())

[[0 5]
 [1 6]
 [2 7]
 [3 8]
 [4 9]]


The `T` attribute has no effect on rank 0 (empty) or rank 1 arrays:

In [4]:
m2 = np.arange(5)
print(m2)
print('\n')
print(m2.T)

[0 1 2 3 4]


[0 1 2 3 4]


We can get the desired transposition by first reshaping the 1D array to a single-row matrix (2D):

In [5]:
m2r = m2.reshape(1,5)
print(m2r)
print('\n')
print(m2r.T)

[[0 1 2 3 4]]


[[0]
 [1]
 [2]
 [3]
 [4]]


# Multiplicación de matrices .dot() y @


In [6]:
n1 = np.arange(10).reshape(2, 5)
print(n1)
print('\n')
n2 = np.arange(15).reshape(5,3)
print(n2)

[[0 1 2 3 4]
 [5 6 7 8 9]]


[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]]


In [7]:
n1.dot(n2)  # el resultado debe dar una matriz de 2 x 3

array([[ 90, 100, 110],
       [240, 275, 310]])

In [8]:
print(n1 @ n2) # el @ es la operación equivalente a .dot()

[[ 90 100 110]
 [240 275 310]]


# la inversa y la pseudo- inversa de una matriz

## np.linalg.inv()

## Docstring:

print(value, ..., sep=' ', end='\n', file=sys.stdout, flush=False)

Prints the values to a stream, or to sys.stdout by default.

Optional keyword arguments:

**file**:  a file-like object (stream); defaults to the current sys.stdout.

**sep**:   string inserted between values, default a space.

**end**:   string appended after the last value, default a newline.

**flush**: whether to forcibly flush the stream.

**Type**:      builtin_function_or_method

In [10]:
m3 = np.array([[1,2,3],[5,7,11],[21,29,31]])

print(m3)
print('\n')
print(np.linalg.inv(m3))

[[ 1  2  3]
 [ 5  7 11]
 [21 29 31]]


[[-2.31818182  0.56818182  0.02272727]
 [ 1.72727273 -0.72727273  0.09090909]
 [-0.04545455  0.29545455 -0.06818182]]


## np.linalg.pinv()

### Signature: 

**np.linalg.pinv(a, rcond=1e-15, hermitian=False)**

### Docstring:

Compute the (Moore-Penrose) pseudo-inverse of a matrix.

Calculate the generalized inverse of a matrix using its
singular-value decomposition (SVD) and including all
*large* singular values.

### Parameters
----------
**a** : (..., M, N) array_like
    Matrix or stack of matrices to be pseudo-inverted.
    
**rcond** : (...) array_like of float
    Cutoff for small singular values.
    Singular values less than or equal to
    ``rcond * largest_singular_value`` are set to zero.
    Broadcasts against the stack of matrices.
    
**hermitian** : bool, optional
    If True, `a` is assumed to be Hermitian (symmetric if real-valued),
    enabling a more efficient method for finding singular values.
    Defaults to False.

### Returns
-------
B : (..., N, M) ndarray

In [12]:
np.linalg.pinv(m3)

array([[-2.31818182,  0.56818182,  0.02272727],
       [ 1.72727273, -0.72727273,  0.09090909],
       [-0.04545455,  0.29545455, -0.06818182]])

# Determinant: np.linalg.det()



In [15]:
print(m3)
print(np.linalg.det(m3))

[[ 1  2  3]
 [ 5  7 11]
 [21 29 31]]
43.99999999999997


# eigenvalues y eigenvectors: np.linalg.eig()

para sacar los autovalores y autovectores de una matriz

In [16]:
eig_val, eig_vec = np.linalg.eig(m3)
print(eig_val) # λ
print('\n')
print(eig_vec) # v

[42.26600592 -0.35798416 -2.90802176]


[[-0.08381182 -0.76283526 -0.18913107]
 [-0.3075286   0.64133975 -0.6853186 ]
 [-0.94784057 -0.08225377  0.70325518]]


 La siguiente multiplicación debería dar una matriz 0

In [18]:
m3.dot(eig_vec) - eig_val*eig_vec # se puede observar qeu todos los valores son casi 0

array([[ 6.21724894e-15,  1.66533454e-15, -3.10862447e-15],
       [ 3.55271368e-15,  5.30131494e-15, -5.32907052e-15],
       [ 3.55271368e-14,  5.38458167e-15, -9.76996262e-15]])