In [1]:
import numpy as np

# Argumentos de un array

Docstring:
array(object, dtype=None, *, copy=True, order='K', subok=False, ndmin=0,
      like=None)

Create an array.

Parameters
----------
**object** : array_like
    An array, any object exposing the array interface, an object whose
    __array__ method returns an array, or any (nested) sequence.
    If object is a scalar, a 0-dimensional array containing object is
    returned.
    
    
**dtype** : data-type, optional
    The desired data-type for the array.  If not given, then the type will
    be determined as the minimum type required to hold the objects in the
    sequence.
    
**copy** : bool, optional
    If true (default), then the object is copied.  Otherwise, a copy will
    only be made if __array__ returns a copy, if obj is a nested sequence,
    or if a copy is needed to satisfy any of the other requirements
    (`dtype`, `order`, etc.).
    
**order** : {'K', 'A', 'C', 'F'}, optional
    Specify the memory layout of the array. If object is not an array, the
    newly created array will be in C order (row major) unless 'F' is
    specified, in which case it will be in Fortran order (column major).
    If object is an array the following holds.

    ===== ========= ===================================================
    order  no copy                     copy=True
    ===== ========= ===================================================
    'K'   unchanged F & C order preserved, otherwise most similar order
    'A'   unchanged F order if input is F and not C, otherwise C order
    'C'   C order   C order
    'F'   F order   F order
    ===== ========= ===================================================

    When ``copy=False`` and a copy is made for other reasons, the result is
    the same as if ``copy=True``, with some exceptions for 'A', see the
    Notes section. The default order is 'K'.
    
    
**subok** : bool, optional
    If True, then sub-classes will be passed-through, otherwise
    the returned array will be forced to be a base-class array (default).
    
**ndmin** : int, optional
    Specifies the minimum number of dimensions that the resulting
    array should have.  Ones will be prepended to the shape as
    needed to meet this requirement.
    
**like** : array_like, optional
    Reference object to allow the creation of arrays which are not
    NumPy arrays. If an array-like passed in as ``like`` supports
    the ``__array_function__`` protocol, the result will be defined
    by it. In this case, it ensures the creation of an array object
    compatible with that passed in via this argument.


# np.zeros

crea un array de las dimensiones indicadas y lo llena de zeros

In [2]:
np.zeros(5)                      # crea un vector linea de 5 zeros

array([0., 0., 0., 0., 0.])

In [3]:
np.zeros((3,4))                  # crea un array de zeros de n x m 

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

## arrays n-dimensionales

In [17]:
np.zeros((2,3,4))

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

## atributos básicos de los arrays

In [5]:
a = np.zeros((3,4))
print(a)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [6]:
a.shape                         # nos devuelve cada axis del array, en este caso (n,m)

(3, 4)

In [7]:
a.ndim                          # devuelve el rango (rank) del array

2

In [8]:
a.size

12

# np.ones

Exactamente lo mismo que zeros pero con 1s

In [9]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

# np.full

Crea un array de las dimensiones indicadas todo lleno con el mismo número

In [10]:
np.full((3,4), np.pi)

array([[3.14159265, 3.14159265, 3.14159265, 3.14159265],
       [3.14159265, 3.14159265, 3.14159265, 3.14159265],
       [3.14159265, 3.14159265, 3.14159265, 3.14159265]])

# np.empty

crea un array de las dimensiones indicadas y lo llena con lo que sea que haya en memoria en ese momento

In [12]:
np.empty((2,4))

array([[0.00e+000, 0.00e+000, 0.00e+000, 0.00e+000],
       [0.00e+000, 8.18e-321, 0.00e+000, 0.00e+000]])

# np.array 

Creamos un array de manera manual

In [18]:
np.array([[1,2,3,4], [10,20,30,40]], )

array([[ 1,  2,  3,  4],
       [10, 20, 30, 40]])

In [16]:
# np.array([[1,2,3,4], [10,20,30]])  # esto da error

In [22]:
np.array([[1,2,3,4], [10,20,30,40]], dtype= 'float')  # se le puede especificar el tipu de numero que queremos que guarde

array([[ 1.,  2.,  3.,  4.],
       [10., 20., 30., 40.]])