In [1]:
import numpy as np

# Broadcasting

En general, numpy espera operaciones para arrays de las misma dimensiones y/o forma, sin embargo, cuando este no es el caso se aplican una serie de reglas de broadcasting.

Al operar con dos matrices, NumPy compara sus formas por elementos. Empieza por la dimensión más a la derecha y sigue hacia la izquierda. Dos dimensiones son compatibles cuando

   1. son iguales, o

   2. una de ellas es 1.

Si no se cumplen estas condiciones, se lanza una excepción ValueError: operands could not be broadcast together, indicando que las matrices tienen formas incompatibles.

No es necesario que las matrices de entrada tengan el mismo número de dimensiones. La matriz resultante tendrá el mismo número de dimensiones que la matriz de entrada con el mayor número de dimensiones, donde el tamaño de cada dimensión es el mayor tamaño de la dimensión correspondiente entre las matrices de entrada. Tenga en cuenta que se supone que las dimensiones que faltan tienen tamaño uno.

<img src= 'broadcasting.png'>
<img src= 'broadcasting_2.png'>

## Regla 1 

**Si las matrices no tienen el mismo rango, se añadirá un 1 a las matrices de menor rango hasta que sus rangos coincidan.**

In [17]:
h = np.arange(5).reshape(1, 1, 5)
print(h, h.ndim, h.shape)

[[[0 1 2 3 4]]] 3 (1, 1, 5)


Ahora vamos a intentar añadir una matriz 1D de forma `(5,)` a esta matriz 3D de forma `(1,1,5)`. 

In [18]:
a = np.array([10, 20, 30, 40, 50])
print(a, a.ndim, a.shape)

[10 20 30 40 50] 1 (5,)


In [10]:
h + a

array([[[10, 21, 32, 43, 54]]])

## Regla 2

**Las matrices con un 1 a lo largo de una dimensión determinada actúan como si tuvieran el tamaño de la matriz con la forma más grande a lo largo de esa dimensión. El valor del elemento de la matriz se repite a lo largo de esa dimensión**

In [11]:
k = np.arange(6).reshape(2, 3)
k

array([[0, 1, 2],
       [3, 4, 5]])

Intentemos añadir un array 2D de forma `(2,1)` a este `ndarray` 2D de forma `(2, 3)`.

In [12]:
k + [[100], [200]]  # same as: k + [[100, 100, 100], [200, 200, 200]]

array([[100, 101, 102],
       [203, 204, 205]])

In [13]:
# aqui se combinan la regla 1 y la 2

k + [100, 200, 300]  # after rule 1: [[100, 200, 300]], and after rule 2: [[100, 200, 300], [100, 200, 300]]

array([[100, 201, 302],
       [103, 204, 305]])

In [15]:
# y aún más simple

k + 10000

array([[10000, 10001, 10002],
       [10003, 10004, 10005]])

## Regla 3 

**Despues de las reglas 2 y 1 las formas de todos los arrays deben coincidir**

In [19]:
try:
    k + [33, 44]
except ValueError as e:
    print(e)

operands could not be broadcast together with shapes (2,3) (2,) 


# Upcasting

Al tratar de combinar matrices con diferentes `dtype`s, NumPy *upcast* a un tipo capaz de manejar todos los valores posibles (independientemente de lo que los valores *actual* son)

In [20]:
k1 = np.arange(0, 5, dtype=np.uint8)
print(k1.dtype, k1)

uint8 [0 1 2 3 4]


In [21]:
k2 = k1 + np.array([5, 6, 7, 8, 9], dtype=np.int8)
print(k2.dtype, k2)

int16 [ 5  7  9 11 13]


Tenga en cuenta que `int16` es necesario para representar todos los *posibles* valores `int8` y `uint8` (de -128 a 255), aunque en este caso hubiera bastado con un `uint8`.

In [22]:
k3 = k1 + 1.5
print(k3.dtype, k3)

float64 [1.5 2.5 3.5 4.5 5.5]
