In [1]:
import numpy as np

# Stacking arrays

A menudo es útil apilar diferentes matrices. NumPy ofrece varias funciones para hacer precisamente eso. Empecemos por crear unas cuantas matrices.

In [2]:
q1 = np.full((3,4), 1.0)
q2 = np.full((4,4), 2.0)
q3 = np.full((3,4), 3.0)
print(q1)
print('\n')
print(q2)
print('\n')
print(q3)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


[[2. 2. 2. 2.]
 [2. 2. 2. 2.]
 [2. 2. 2. 2.]
 [2. 2. 2. 2.]]


[[3. 3. 3. 3.]
 [3. 3. 3. 3.]
 [3. 3. 3. 3.]]


# vstack()


Este metodo concatena arrays verticalmente, se le pasa una tupla con los arrays que queremos concatenar. Estos arrais deben coincidir en el numero de columnas si no, no será posible la concatenación

## Signature: np.vstack(tup)

## Docstring:

Stack arrays in sequence vertically (row wise).

This is equivalent to concatenation along the first axis after 1-D arrays
of shape `(N,)` have been reshaped to `(1,N)`. Rebuilds arrays divided by
`vsplit`.

This function makes most sense for arrays with up to 3 dimensions. For
instance, for pixel-data with a height (first axis), width (second axis),
and r/g/b channels (third axis). The functions `concatenate`, `stack` and
`block` provide more general stacking and concatenation operations.

## Parameters
----------
**tup** : sequence of ndarrays
    The arrays must have the same shape along all but the first axis.
    1-D arrays must have the same length.

## Returns
-------
**stacked** : ndarray
    The array formed by stacking the given arrays, will be at least 2-D.

In [4]:
q4 = np.vstack((q1, q2, q3))
print(q4)
print(q4.shape)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [2. 2. 2. 2.]
 [2. 2. 2. 2.]
 [2. 2. 2. 2.]
 [2. 2. 2. 2.]
 [3. 3. 3. 3.]
 [3. 3. 3. 3.]
 [3. 3. 3. 3.]]
(10, 4)


# hstack()

Lo mismo que vstack pero horizonalmente, los arrays deben coincidir en el número de filas

## Signature: np.hstack(tup)
## Docstring:

Stack arrays in sequence horizontally (column wise).

This is equivalent to concatenation along the second axis, except for 1-D
arrays where it concatenates along the first axis. Rebuilds arrays divided
by `hsplit`.

This function makes most sense for arrays with up to 3 dimensions. For
instance, for pixel-data with a height (first axis), width (second axis),
and r/g/b channels (third axis). The functions `concatenate`, `stack` and
`block` provide more general stacking and concatenation operations.

## Parameters
----------
**tup** : sequence of ndarrays
    The arrays must have the same shape along all but the second axis,
    except 1-D arrays which can be any length.

## Returns
-------
**stacked** : ndarray
    The array formed by stacking the given arrays.

In [6]:
q5 = np.hstack((q1, q3))
print(q5, q5.shape)

[[1. 1. 1. 1. 3. 3. 3. 3.]
 [1. 1. 1. 1. 3. 3. 3. 3.]
 [1. 1. 1. 1. 3. 3. 3. 3.]] (3, 8)


In [7]:
try:
    q5 = np.hstack((q1, q2, q3))
except ValueError as e:
    print(e)

all the input array dimensions for the concatenation axis must match exactly, but along dimension 0, the array at index 0 has size 3 and the array at index 1 has size 4


# concatenate

Es una función que abarca las dos funciones anteriores, sirve para concatenar horizontalmente como verticalmente. Hay que inidicarle el axis: 

- axis = 0 equivalente a vstack
- axis = 1 equivalente a hstack

## Docstring:

**concatenate((a1, a2, ...), axis=0, out=None, dtype=None, casting="same_kind")**

Join a sequence of arrays along an existing axis.

## Parameters
----------
**a1, a2, ...** : sequence of array_like
    The arrays must have the same shape, except in the dimension
    corresponding to `axis` (the first, by default).
    
**axis** : int, optional
    The axis along which the arrays will be joined.  If axis is None,
    arrays are flattened before use.  Default is 0.
    
**out** : ndarray, optional
    If provided, the destination to place the result. The shape must be
    correct, matching that of what concatenate would have returned if no
    out argument were specified.
    
**dtype** : str or dtype
    If provided, the destination array will have this dtype. Cannot be
    provided together with `out`.


**casting** : {'no', 'equiv', 'safe', 'same_kind', 'unsafe'}, optional
    Controls what kind of data casting may occur. Defaults to 'same_kind'.



## Returns
-------
**res** : ndarray
    The concatenated array.

In [9]:
q7 = np.concatenate((q1,q2,q3), axis= 0)
print(q7)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [2. 2. 2. 2.]
 [2. 2. 2. 2.]
 [2. 2. 2. 2.]
 [2. 2. 2. 2.]
 [3. 3. 3. 3.]
 [3. 3. 3. 3.]
 [3. 3. 3. 3.]]


# stack

concatena dos arrays a través de un nuevo 'axis'; todos los arrays deben tener la misma forma - shape.

## Signature: np.stack(arrays, axis=0, out=None)
## Docstring:
Join a sequence of arrays along a new axis.

The ``axis`` parameter specifies the index of the new axis in the
dimensions of the result. For example, if ``axis=0`` it will be the first
dimension and if ``axis=-1`` it will be the last dimension.

.. versionadded:: 1.10.0

## Parameters
----------
**arrays** : sequence of array_like
    Each array must have the same shape.

**axis** : int, optional
    The axis in the result array along which the input arrays are stacked.

**out** : ndarray, optional
    If provided, the destination to place the result. The shape must be
    correct, matching that of what stack would have returned if no
    out argument were specified.

## Returns
-------
**stacked** : ndarray
    The stacked array has one more dimension than the input arrays.

In [13]:
q8 = np.stack((q1, q3), axis= 0)
q8

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.]]])

In [14]:
q8 = np.stack((q1, q3), axis= 1)
q8

array([[[1., 1., 1., 1.],
        [3., 3., 3., 3.]],

       [[1., 1., 1., 1.],
        [3., 3., 3., 3.]],

       [[1., 1., 1., 1.],
        [3., 3., 3., 3.]]])

In [15]:
q8 = np.stack((q1, q3), axis= 2)
q8

array([[[1., 3.],
        [1., 3.],
        [1., 3.],
        [1., 3.]],

       [[1., 3.],
        [1., 3.],
        [1., 3.],
        [1., 3.]],

       [[1., 3.],
        [1., 3.],
        [1., 3.],
        [1., 3.]]])

# np.c_[array1, array2, ...]

Para concatenar columnas, equivalente a hstack

## Docstring:  
Translates slice objects to concatenation along the second axis.

This is short-hand for ``np.r_['-1,2,0', index expression]``, which is
useful because of its common occurrence. In particular, arrays will be
stacked along their last axis after being upgraded to at least 2-D with
1's post-pended to the shape (column vectors made out of 1-D arrays).


In [25]:
np.c_[np.array([1,2,3]), np.array([4,5,6])]

array([[1, 4],
       [2, 5],
       [3, 6]])

In [27]:
np.c_[q1, q3]

array([[1., 1., 1., 1., 3., 3., 3., 3.],
       [1., 1., 1., 1., 3., 3., 3., 3.],
       [1., 1., 1., 1., 3., 3., 3., 3.]])

# np.r_[ array1, array2, ...]

Equivalente a usar vstack

## Docstring:  

Translates slice objects to concatenation along the first axis.

This is a simple way to build up arrays quickly. There are two use cases.

1. If the index expression contains comma separated arrays, then stack
   them along their first axis.
   
2. If the index expression contains slice notation or scalars then create
   a 1-D array with a range indicated by the slice notation.

If slice notation is used, the syntax ``start:stop:step`` is equivalent
to ``np.arange(start, stop, step)`` inside of the brackets. However, if
``step`` is an imaginary number (i.e. 100j) then its integer portion is
interpreted as a number-of-points desired and the start and stop are
inclusive. In other words ``start:stop:stepj`` is interpreted as
``np.linspace(start, stop, step, endpoint=1)`` inside of the brackets.
After expansion of slice notation, all comma separated sequences are
concatenated together.

Optional character strings placed as the first element of the index
expression can be used to change the output. The strings 'r' or 'c' result
in matrix output. If the result is 1-D and 'r' is specified a 1 x N (row)
matrix is produced. If the result is 1-D and 'c' is specified, then a N x 1
(column) matrix is produced. If the result is 2-D then both provide the
same matrix result.

A string integer specifies which axis to stack multiple comma separated
arrays along. A string of two comma-separated integers allows indication
of the minimum number of dimensions to force each entry into as the
second integer (the axis to concatenate along is still the first integer).

A string with three comma-separated integers allows specification of the
axis to concatenate along, the minimum number of dimensions to force the
entries to, and which axis should contain the start of the arrays which
are less than the specified number of dimensions. In other words the third
integer allows you to specify where the 1's should be placed in the shape
of the arrays that have their shapes upgraded. By default, they are placed
in the front of the shape tuple. The third argument allows you to specify
where the start of the array should be instead. Thus, a third argument of
'0' would place the 1's at the end of the array shape. Negative integers
specify where in the new shape tuple the last dimension of upgraded arrays
should be placed, so the default is '-1'.

## Parameters
----------
Not a function, so takes no parameters


## Returns
-------
A concatenated ndarray or matrix.

In [28]:
np.r_[q1, q2, q3]

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [2., 2., 2., 2.],
       [2., 2., 2., 2.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [3., 3., 3., 3.],
       [3., 3., 3., 3.]])

# Splits

Es lo contrario a stack; divide vectores - matrizes. LA DIVISIÓN DEBE RESULTAR EN VECTORES - MATRIZES DE MISMAS DIRECCIONES

# np.vsplit()

Rompe - separa una matriz en diferentes filas

## Signature: 

**np.vsplit(ary, indices_or_sections)**

## Docstring:

Split an array into multiple sub-arrays vertically (row-wise).

Please refer to the ``split`` documentation.  ``vsplit`` is equivalent
to ``split`` with `axis=0` (default), the array is always split along the
first axis regardless of the array dimension.


In [29]:
r = np.arange(24).reshape(6, 4)
print(r)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]


In [32]:
r1, r2, r3 = np.vsplit(r, 3)
print(r1,'\n\n', r2,'\n\n', r3)

[[0 1 2 3]
 [4 5 6 7]] 

 [[ 8  9 10 11]
 [12 13 14 15]] 

 [[16 17 18 19]
 [20 21 22 23]]


# np.hsplit()

Rompe - separa el array por columnas.

## Signature:

**np.hsplit(ary, indices_or_sections)**

## Docstring:

Split an array into multiple sub-arrays horizontally (column-wise).

Please refer to the `split` documentation.  `hsplit` is equivalent
to `split` with ``axis=1``, the array is always split along the second
axis except for 1-D arrays, where it is split at ``axis=0``.

In [33]:
r1, r2, r3, r4 = np.hsplit(r, 4)
print(r1,'\n\n', r2,'\n\n', r3, '\n\n', r4)

[[ 0]
 [ 4]
 [ 8]
 [12]
 [16]
 [20]] 

 [[ 1]
 [ 5]
 [ 9]
 [13]
 [17]
 [21]] 

 [[ 2]
 [ 6]
 [10]
 [14]
 [18]
 [22]] 

 [[ 3]
 [ 7]
 [11]
 [15]
 [19]
 [23]]


# np.split

es el genérico de hsplit y vsplit 

## Signature:

**np.split(ary, indices_or_sections, axis=0)**

## Docstring:

Split an array into multiple sub-arrays as views into `ary`.

Parameters
----------
**ary** : ndarray
    Array to be divided into sub-arrays.
    
**indices_or_sections** : int or 1-D array
    If `indices_or_sections` is an integer, N, the array will be divided
    into N equal arrays along `axis`.  If such a split is not possible,
    an error is raised.

    If `indices_or_sections` is a 1-D array of sorted integers, the entries
    indicate where along `axis` the array is split.  For example,
    ``[2, 3]`` would, for ``axis=0``, result in

      - ary[:2]
      - ary[2:3]
      - ary[3:]

    If an index exceeds the dimension of the array along `axis`,
    an empty sub-array is returned correspondingly.
    
**axis** : int, optional
    The axis along which to split, default is 0.

Returns
-------
**sub-arrays** : list of ndarrays
    A list of sub-arrays as views into `ary`.

In [36]:
np.split(r, 2, axis= 1)

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13],
        [16, 17],
        [20, 21]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15],
        [18, 19],
        [22, 23]])]

In [37]:
type(np.split(r, 2, axis= 1))

list